[phases.setup]
nixPkgs = ["nodejs_20", "postgresql"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = [
  "npm run build -w apps/backend",
  "npx prisma generate --schema=apps/backend/prisma/schema.prisma",
  "npx prisma migrate deploy --schema=apps/backend/prisma/schema.prisma"
]

[start]
cmd = "cd apps/backend && npm run start:prod"

