[phases.setup]
nixPkgs = ["nodejs_20", "postgresql"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = [
  "npm run build -w apps/backend", 
  "cd apps/backend && npx prisma generate",
  "cd apps/backend && npx prisma migrate deploy"
]

[start]
cmd = "cd apps/backend && npm run start:prod"

